version: '3.9'

services:
  template:
    build: .
    environment:
      SECRET_FILE: /run/secrets/secret
      FOO: ${FOO}
    secrets:
      - secret
    env_file:
      - .env-sample
    ports:
      - '8080:8080'

secrets:
  secret:
    file: .secret-sample
